### ISSUE TITLE
Swagger description tag 

### ISSUE THREAD

**Issue by shmerskawven07** [redlab/swagger-jaxb#10]
Hi, 

Where to put the description in the xsd to have it in the @ApiModelProperty? 

like this : @ApiModelProperty(value = "id", required = true, description="where did this come from")

Thanks

**Comment by redlab** [comment]
I have not added something for description. Feel free to propose something.

**Comment by JohneDoe** [comment]
add Description of Element into Notes of ApiModelProperty #3

@ApiModelProperty(name="propertyName", notes="value of xs:annotationxs:documentation..")

**Comment by redlab** [comment]
@JohneDoe It's a bit busy at work at the moment but I'll look into adding that

**Comment by redlab** [comment]
added by PR https://github.com/redlab/swagger-jaxb/pull/12
